### ISSUE TITLE
cannot access to vgg.pkl

### ISSUE THREAD

**Issue by Carbord** [imatge-upc/salgan#40]
Hi, I  am impressed by this work and I want to use the pre-trained model to produce saliency maps for some other images. However, I have trouble trying to download the vgg.pkl perheps the foreign server is denied by my browser in China. So I wonder if anyone is kind to share the model to me or offer other links to download the vgg.pkl, for which I will be greatly grateful.

**Comment by Fanshia** [comment]
Me too

**Comment by xavigiro** [comment]
We just published it. You can download it from [here](https://imatge.upc.edu/web/sites/default/files/resources/1720/saliency/2017-salgan/vgg16.pkl).
